name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f infra/docker-compose.development.yml up -d

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run build
      - run: npm start & npm run test:ci

      - name: Stop containers
        if: always()
        run: docker-compose -f infra/docker-compose.development.yml down
